### ISSUE TITLE
Analyse ergänzen

### ISSUE THREAD

**Issue by s72785** [SemAhto/Projektdokumentation#15]
* [x] Quellen Spirale/Positionierung
  + [x] http://static.mrfeinberg.com/bv_ch03.pdf – als `misc:wordle` verfügbar
  + [x] zitieren
  + [x] [Vortragsfolien TagCloudDrawing](https://de.slideshare.net/lemire/tagcloud-drawing-algorithms-for-cloud-visualization-presentation) als `misc:TagCloudDrawing` dabei
  + [x] zitieren
* [x] Lizenzen
* [ ] Recherche zur Positionierung in Analyse s.a. https://pad.fsfw-dresden.de/p/visualisierung-wordcloud , https://pad.fsfw-dresden.de/p/161018-tagcloud-arlgo-presentation – entfällt wahrscheinlich
* [ ] Recherche Implementationen – entfällt wahrscheinlich 
* [ ] Möglichkeiten Einbinden/Aufrufen von Implementationen in anderen Programmiersprachen aus Java, s.a. https://pad.fsfw-dresden.de/p/java-in-csharp – entfällt wahrscheinlich

**Comment by pblaskoda** [comment]
Quelle Spirale/Positionerung: 
https://de.wikipedia.org/wiki/Spirale
https://de.wikipedia.org/wiki/Archimedische_Spirale

**Comment by pblaskoda** [comment]
Recherche zur Positionierung in Analyse s.a. pads aus trello
meiner Meinung nach in Herangehensweisen der Tag-Cloud-Erstellung

**Comment by pblaskoda** [comment]
zu Möglichkeiten Einbinden/Aufrufen von Implementationen in anderen Programmiersprachen aus Java:

damit habe ich mich zwar beschäftigt, Programmcode den ich dazu genutzt habe, weiß ich nicht mehr. 
Weil es zu komplex war/ist und wir nicht noch eine Schnittstelle mit einbeziehen wollten, fiel es als Verfahren aus.

**Comment by pblaskoda** [comment]
Quellen für Implementation:
- https://de.slideshare.net/lemire/tagcloud-drawing-algorithms-for-cloud-visualization-presentation
- http://static.mrfeinberg.com/bv_ch03.pdf

**Comment by pblaskoda** [comment]
Links aus Trello für diverse Pads:
- https://pad.fsfw-dresden.de/p/161018-tagcloud-arlgo-presentation
- https://pad.fsfw-dresden.de/p/java-in-csharp
- https://pad.fsfw-dresden.de/p/visualisierung-wordcloud

**Comment by s72785** [comment]
Egal ob Java oder was anderes, wir hatten demonstriert, dass wir aus C# heraus über Shell-Aufrufe andere Programme steuern und die Ausgabe nutzen können. Aber die Absage an diesen Ansatz durch neolithos war ziemlich fix, da dies mehr technologischen Ballast bringt und nicht mit der Performance einer nativen C#-Umsetzung mithalten kann.

**Comment by s72785** [comment]
gut zu wissen, wontfix
