### ISSUE TITLE
Projektdoku_Fehler

### ISSUE THREAD

**Issue by pblaskoda** [SemAhto/Projektdokumentation#9]
* [x] Seite ii, Punkt 6.1 --> da ist die Nummerierung 3.1 viel
* [x] **Q:** allgemeine Frage zur Nummerierung: Muss da nicht immer ein Punkt zum Schluss dran, also z.B. 2. , 2.1. – **A:** Nein.
* [x] Seite 1 , Zeile 2 da fehlt ein Bindestrich bei Tag-Cloud – done
* [x] Seite 5, Punkt 3.3 Eingabe großschreiben – done
* [x] Seite 5, Punkt 3.3  erste Zeile das abschließende "s" bei Systems ist zu viel – done
* [x] Seite 8 Punkt 4 (Text Mining), "Algorthimus-basierten" da fehlt ein i – done
* [x] Seite 10 Elastiksearch mit c oder k, zwei unterschiedliche Schreibweisen im Text – done, mit 'c'
* [x] Seite 10 Schreibfehler in der Aufzählung Sktech Engine – done
* [ ] Seite 12, Ende zweiter Absatz "###" ?  – unklar, wahrscheinlich schon behoben

**Comment by s72785** [comment]
sehe ich mal als erledigt an
